version: "3.8"

services:
  app:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.${AWS_REGION}.amazonaws.com/agenda-editor-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always